version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql_data/data

  application:
    container_name: parser
    build:
      context: .
    env_file:
      - .env
    command: python3 main.py
    depends_on:
      - db

volumes:
  mysql_data: